# Environment variables defined in a calling workflow are not accessible to this reusable workflow. Refer to the documentation for further details on this limitation.
name: project_1_ci_build
on:
  workflow_call:
    inputs:
      agentPool:
        required: false
        default: ''
        type: string
      agentImage:
        required: false
        default: ''
        type: string
      artifacts:
        required: false
        default: ''
        type: string
jobs:
  Artifacts:
    runs-on: ${{ inputs.agentImage }}
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/checkout@v4.1.0
    - name: Publish Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        path: "${{ inputs.artifacts }}"
