name: deployment-2-file-second

on:
  workflow_call:
    inputs:
      DEPLOYMENTSTAGE:
        required: true
        type: string
      SUBSCRIPTIONID:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy resource group
      - name: deploy-resource-group
        id: deploy-1
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ inputs.SUBSCRIPTIONID }}
          template: ./scripts/createresourcegroup.json
          parameters: ./scripts/createresourcegroup-project1.${{ inputs.DEPLOYMENTSTAGE }}.param.json
          region: westeurope

      - run: echo ${{ steps.deploy-1.outputs.ResourceGroupName }}

      # Deploy ARM template - https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-github-actions?tabs=userlevel
      - name: deploy-template
        id: deploy-2
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ inputs.SUBSCRIPTIONID }}
          resourceGroupName: ${{ steps.deploy-1.outputs.ResourceGroupName }}
          template: ./scripts/storage.json
          parameters: ./scripts/storage-diag001.${{ inputs.DEPLOYMENTSTAGE }}.param.json

      - run: echo ${{ steps.deploy-2.outputs.storageAccountName }}